spring:
  config:
    activate:
      on-profile: "local"

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        default_batch_insert_size: 10000
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
